CREATE TABLE address
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street_address VARCHAR(255),
    city           VARCHAR(255),
    state          VARCHAR(255),
    zip_code       VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);