CREATE TABLE token
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255),
    token_type VARCHAR(255),
    expired    BOOLEAN NOT NULL,
    revoked    BOOLEAN NOT NULL,
    user_id    INTEGER,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

ALTER TABLE token
    ADD CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES _user (id);