CREATE TABLE agent
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    contact_info VARCHAR(255),
    email        VARCHAR(255),
    image        VARCHAR(255),
    rating       VARCHAR(255),
    CONSTRAINT pk_agent PRIMARY KEY (id)
);