spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cacttus
    username: cacttus
    password: cacttus
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 8585D3952BEE2B1B0B6BE222CDDB185D867EB67025107E6FDFF5027168A372D6116591ACA37C6D87B1E4A5A7E53C7A58C4D48FA3AF5F749B83CCED50F432688E428B6976F526F0E3F0296EBB2643114FC1661C817E2593E494342E6F8EF54F4B5C31AF211694D5AD6E41E257C3C339490375284AB008A1D0D31214A766D87688
      expiration: 86400000  # a day
      refresh-token:
        expiration: 604800000 # 7 days







